# Generated by Django 5.2.17 on 2026-09-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0015_arena"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenacomparison",
            name="champion_committed",
            field=models.BooleanField(
                default=False,
                help_text="The champion answer is already in the conversation history. It is written as soon as the champion finishes so nothing is lost if the user never votes; a vote for the challenger swaps it.",
            ),
        ),
        migrations.AlterField(
            model_name="arenacomparison",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comparisons",
                to="chat.arenaexperiment",
            ),
        ),
    ]
