# Generated by Django 5.2.17 on 2026-09-16 08:20

from django.db import migrations, models


def repair_legacy_comparisons(apps, schema_editor):
    """Do not resume unsnapshotted runs; erase content from previously deleted chats."""
    comparison = apps.get_model("chat", "ArenaComparison")
    rows = comparison.objects.using(schema_editor.connection.alias)
    rows.filter(status="pending").update(status="errored", closed_reason="legacy_interrupted")
    rows.filter(status="abandoned").exclude(challenger_error="").update(
        status="errored", closed_reason="candidate_failed"
    )
    rows.filter(conversation__isnull=True, is_seed=False).update(
        user=None,
        champion_payload=None,
        challenger_payload=None,
        champion_trace_id="",
        challenger_trace_id="",
        theme="",
        champion_error="",
        challenger_error="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_arena_draw_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="arenacomparison",
            name="challenger_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="champion_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="closed_reason",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="conversation_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="input_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="price_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="arena_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(repair_legacy_comparisons, migrations.RunPython.noop),
    ]
