# Generated by Django 5.2.17 on 2026-09-16 15:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0018_arena_reliability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingTierSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "simple_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier 1 model. Blank means 'use the LLM_TIER_*_MODEL_HRID setting', which itself defaults to LLM_DEFAULT_MODEL_HRID.",
                        max_length=100,
                    ),
                ),
                (
                    "simple_alternatives",
                    models.JSONField(
                        blank=True, default=list, help_text="HRIDs of the tier 1 alternatives."
                    ),
                ),
                (
                    "standard_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier 2 model. Blank means 'use the LLM_TIER_*_MODEL_HRID setting', which itself defaults to LLM_DEFAULT_MODEL_HRID.",
                        max_length=100,
                    ),
                ),
                (
                    "standard_alternatives",
                    models.JSONField(
                        blank=True, default=list, help_text="HRIDs of the tier 2 alternatives."
                    ),
                ),
                (
                    "complex_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier 3 model. Blank means 'use the LLM_TIER_*_MODEL_HRID setting', which itself defaults to LLM_DEFAULT_MODEL_HRID.",
                        max_length=100,
                    ),
                ),
                (
                    "complex_alternatives",
                    models.JSONField(
                        blank=True, default=list, help_text="HRIDs of the tier 3 alternatives."
                    ),
                ),
                (
                    "router_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Classifier model. Blank means 'use the LLM_ROUTER_MODEL_HRID setting'.",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Tiers 1 and 3 are chosen only at or above this classifier confidence.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "high_effort_threshold",
                    models.FloatField(
                        default=0.9,
                        help_text="Tier 3 runs at high reasoning effort at or above this confidence.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "tier_energy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per tier: {wh_per_answer, n, source: estimated|measured, updated_at}. Refreshed from Langfuse by the refresh_tier_energy command.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Tier Settings",
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="last_routing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Routing decision of the last turn (tier, model_hrid and classifier labels), used as a hint by the router on the next turn.",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="pinned_tier",
            field=models.CharField(
                blank=True,
                choices=[("simple", "SIMPLE"), ("standard", "STANDARD"), ("complex", "COMPLEX")],
                help_text="Complexity tier the user pinned on this conversation (router spec 5.3). Null means Auto: the router picks the tier on every turn.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RoutingTierHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("simple", "SIMPLE"),
                            ("standard", "STANDARD"),
                            ("complex", "COMPLEX"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("promotion", "Promotion"),
                            ("threshold", "Threshold"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_value", models.TextField(blank=True, default="")),
                ("to_value", models.TextField(blank=True, default="")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Experiment id, votes, win rate, confidence interval, Wh ratio...",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_tier_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Routing tier history",
                "ordering": ["-changed_at"],
            },
        ),
    ]
