# Generated by Django 5.2.17 on 2026-09-16 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0019_routing_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arenaexperiment",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_arena_results", "Can view arena results"),
                    (
                        "promote_routing_champion",
                        "Can promote an arena challenger to the tier model",
                    ),
                ],
            },
        ),
        migrations.RemoveField(
            model_name="arenacomparison",
            name="theme",
        ),
        migrations.RemoveField(
            model_name="arenaexperiment",
            name="champion_model_hrid",
        ),
        migrations.AddField(
            model_name="arenachallenger",
            name="is_control",
            field=models.BooleanField(
                default=False,
                help_text="Out-of-tier control challenger used only to tune the classifier threshold (router spec 5.4). Drawn on 5% of the experiment's draws, excluded from the challenger scoreboard and from promotion, shown in its own column.",
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="challenger_co2_source",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="challenger_reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[("medium", "MEDIUM"), ("high", "HIGH")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="challenger_reasoning_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="champion_co2_source",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="champion_reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[("medium", "MEDIUM"), ("high", "HIGH")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="champion_reasoning_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "GENERAL"),
                    ("administrative", "ADMINISTRATIVE"),
                    ("legal", "LEGAL"),
                    ("health", "HEALTH"),
                    ("finance", "FINANCE"),
                    ("hr", "HR"),
                    ("it_software", "IT_SOFTWARE"),
                    ("science_education", "SCIENCE_EDUCATION"),
                    ("communication", "COMMUNICATION"),
                    ("defense_security", "DEFENSE_SECURITY"),
                    ("environment", "ENVIRONMENT"),
                    ("culture_society", "CULTURE_SOCIETY"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="origin",
            field=models.CharField(
                choices=[("draw", "DRAW"), ("manual", "MANUAL")],
                default="draw",
                help_text="draw: sampled by the arena. manual: asked for with the second-opinion button.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="router_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="router_model_hrid",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="router_prompt_version",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="router_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("classified", "CLASSIFIED"),
                    ("shortcut", "SHORTCUT"),
                    ("constraint", "CONSTRAINT"),
                    ("constraint_fallback", "CONSTRAINT_FALLBACK"),
                    ("fallback", "FALLBACK"),
                    ("user_pinned", "USER_PINNED"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="task",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qa_knowledge", "QA_KNOWLEDGE"),
                    ("writing", "WRITING"),
                    ("summarization", "SUMMARIZATION"),
                    ("translation", "TRANSLATION"),
                    ("coding", "CODING"),
                    ("data_analysis", "DATA_ANALYSIS"),
                    ("document_qa", "DOCUMENT_QA"),
                    ("research", "RESEARCH"),
                    ("reasoning", "REASONING"),
                    ("brainstorm_creative", "BRAINSTORM_CREATIVE"),
                    ("classification_extraction", "CLASSIFICATION_EXTRACTION"),
                    ("conversation", "CONVERSATION"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[("simple", "SIMPLE"), ("standard", "STANDARD"), ("complex", "COMPLEX")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="arenacomparison",
            name="tier_source",
            field=models.CharField(
                blank=True,
                choices=[("router", "ROUTER"), ("user", "USER"), ("constraint", "CONSTRAINT")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="arenaexperiment",
            name="reasoning_effort",
            field=models.CharField(
                blank=True,
                choices=[("medium", "MEDIUM"), ("high", "HIGH")],
                help_text="Forces both sides of a tier 3 experiment to this reasoning effort. Empty means the router's per-turn effort applies to both sides.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="arenaexperiment",
            name="tier",
            field=models.CharField(
                choices=[("simple", "SIMPLE"), ("standard", "STANDARD"), ("complex", "COMPLEX")],
                default="standard",
                help_text="Complexity tier this experiment runs on. The champion is that tier's model in the routing tier settings; challengers are drawn from its alternatives.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="arenacomparison",
            index=models.Index(
                fields=["conversation", "turn"], name="chat_arenac_convers_153002_idx"
            ),
        ),
    ]
